E_Commerce/E_Commerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('E_Commerce_App.urls')),
]

E_Commerce/E_Commerce_App/urls.py
from django.urls import path
from E_Commerce_App import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', views.index, name='index'),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

E_Commerce/E_Commerce_App/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name

class Sub_Category(models.Model):
    name = models.CharField(max_length=150)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    def __str__(self):
        return self.name
    

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=False, default='')
    sub_category = models.ForeignKey(Sub_Category, on_delete=models.CASCADE, null=False,default='')
    image = models.ImageField(upload_to='ecommerce/pimg')
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name
    

E_Commerce/E_Commerce_App/views.py
from django.shortcuts import render
from E_Commerce_App.models import Category, Product
# Create your views here.
def index(request):
    category = Category.objects.all()
    product = Product.objects.all()
    categoryID = request.GET.get('category')
    if categoryID:
        product = Product.objects.filter(sub_category = categoryID)
    else:
        product = Product.objects.all()
    context = {
        'category': category,
        'product': product
    }
    return render(request, 'index.html', context)

E_Commerce/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="static/css/style.css" />
    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    <nav class="navbar">
      <div class="logo">
        <h1>E SHOP</h1>
      </div>
      <ul>
        <li><a href="/">Home</a></li>
        <li><a href="">About Us</a></li>
        <li><a href="">Contact Us</a></li>
        <li><a href="">Login</a></li>
        <li><a href="">Register</a></li>
        <li><a href="">Logout</a></li>
      </ul>
      <div class="cart">
        <button id="cart" onclick="ShowCart(true)"><img src="static/images/add-to-cart.png" alt="" id="imgcart"/></button
        ><span id="cart-count">0</span>
      </div>
    </nav>

    {% block body %}
    
    {% endblock body %}

    <div class="footer">
      <!-- Footer content -->
      <p>&copy; 2023 Your Company. All rights reserved.</p>
    </div>

    <script src="static/js/script.js"></script>
  </body>
</html>

E_Commerce/templates/index.html
{% extends 'base.html' %} {% block title %}Home{% endblock title %} 
{% block body %}
<main>
  <section class="products">
    {% for prod in product %}
    <div class="product">
      <img src="{{prod.image}}" alt="Product 1" style="height: 200px" />
      <h3>{{prod.name}}</h3>
      <p>{{prod.price}}</p>
      <form>
        <input 
          type="hidden" 
          value="{{prod.id}}" 
          id="prodid_{{prod.id}}" 
          />
        <input
          type="hidden"
          value="{{prod.name}}"
          id="prodname_{{prod.name}}"
        />
        <input
          type="hidden"
          value="{{prod.price}}"
          id="prodprice_{{prod.price}}"
        />

        <button
          class="add-to-cart"
          onclick="addToCart('{{prod.id}}','{{prod.name}}','{{prod.price}}')"
        >
          Add to Cart
        </button>
      </form>
    </div>
    {% endfor %}
  </section>

  <section class="categories">
    <h2>Categories</h2>
    {% for cat in category %} {{cat.name}}
    <ul class="subCategory">
      {% for sub_cat in cat.sub_category_set.all %}
      <a href="/?category={{sub_cat.id}}">{{sub_cat.name}}</a>
      {% endfor %}
    </ul>
    {% endfor %}
  </section>
</main>

<div id="cart-items_" 
style=" width: 300px; height: 200px; background-color: lightgreen;
text-align:center;
    padding: 20px;
    margin: auto;
    position: fixed;
    right:0;
    top:0;margin-top: 60px;
    display:none;
    overflow: auto;">
  
<div id="cart-items_details" style="padding: 10px; margin: 10px"></div>

  <p id="total-amount">Total Amount: $0.00</p>

  <button onclick="hidecart()" style="margin-top: 50px;">
    Close
  </button>
  <span><button onclick="emptyCart()">Empty Cart</button></span>
</div>

{% endblock body %}